/* Autogenerated by png2wx.pl on Mon May 23 13:54:18 2011 */
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>
#include "ocpn_plugin.h"
#include "icons.h"

// wxString _svg_vdr_pi;
wxString _svg_vdr;
wxString _svg_vdr_play;
wxString _svg_vdr_record;
wxString _svg_record_toggled;
wxString _svg_record_rollover;
wxString _svg_play_toggled;
wxString _svg_play_rollover;

wxString _svg_settings;
wxString _svg_file_open;
wxString _svg_play_circle;
wxString _svg_pause_circle;
wxString _svg_stop_circle;

void initialize_images(void) {
  wxFileName fn;
  wxString tmp_path;
  tmp_path = GetPluginDataDir("vdr_pi");
  fn.SetPath(tmp_path);
  fn.AppendDir(_T("data"));

  fn.SetFullName(_T("vdr_pi.svg"));
  _svg_vdr = fn.GetFullPath();

  fn.SetFullName(_T("vdr_play.svg"));
  _svg_vdr_play = fn.GetFullPath();

  fn.SetFullName(_T("vdr_record.svg"));
  _svg_vdr_record = fn.GetFullPath();

  fn.SetFullName(_T("vdr_play_rollover.svg"));
  _svg_play_rollover = fn.GetFullPath();

  fn.SetFullName(_T("vdr_play_toggled.svg"));
  _svg_play_toggled = fn.GetFullPath();

  fn.SetFullName(_T("vdr_record_rollover.svg"));
  _svg_record_rollover = fn.GetFullPath();

  fn.SetFullName(_T("vdr_record_toggled.svg"));
  _svg_record_toggled = fn.GetFullPath();

  fn.SetFullName(_T("vdr_settings.svg"));
  _svg_settings = fn.GetFullPath();

  fn.SetFullName(_T("vdr_file_open.svg"));
  _svg_file_open = fn.GetFullPath();

  fn.SetFullName(_T("vdr_play_circle.svg"));
  _svg_play_circle = fn.GetFullPath();

  fn.SetFullName(_T("vdr_pause_circle.svg"));
  _svg_pause_circle = fn.GetFullPath();

  fn.SetFullName(_T("vdr_stop_circle.svg"));
  _svg_stop_circle = fn.GetFullPath();

  wxLogMessage(_T("Loading toolbar icon: ") + _svg_record_toggled);

  return;
}
