/* Autogenerated by png2wx.pl on Mon May 23 13:54:18 2011 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

#include <wx/bitmap.h>
#include <wx/string.h>

#include "config.h"

extern void initialize_images(void);

extern wxString _svg_vdr;
extern wxString _svg_vdr_play;
extern wxString _svg_vdr_record;
extern wxString _svg_play_rollover;
extern wxString _svg_play_toggled;
extern wxString _svg_record_rollover;
extern wxString _svg_record_toggled;

extern wxString _svg_settings;
extern wxString _svg_file_open;
extern wxString _svg_play_circle;
extern wxString _svg_pause_circle;
extern wxString _svg_stop_circle;

#endif /* ICONS_H */
